name: Build, Test and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: satackey/action-docker-layer-caching@v0.0.8
        continue-on-error: true
        with:
          key: bbzw-docker-cache-{hash}
          restore-keys: |
            bbzw-docker-cache-
      - run: docker build -t registry.heroku.com/bbzw-chat/web ${GITHUB_WORKSPACE}
      - shell: bash
        env:
          AUTH_TOKEN: ${{ secrets.HEROKU_AUTH_TOKEN }}
        run: |
          docker login --username=_ --password=${AUTH_TOKEN} registry.heroku.com
      - run: docker push registry.heroku.com/bbzw-chat/web
      - uses: akhileshns/heroku-deploy@v3.6.8 # This is the action
        with:
          heroku_api_key: ${{ secrets.HEROKU_AUTH_TOKEN }}
          heroku_app_name: "bbzw-chat"
          heroku_email: "mail@adrianimboden.ch"
          justlogin: true
      - run: heroku container:release web -a bbzw-chat
